#!/usr/bin/env python3

# Created by: Roman Cernetchi
# Created on: January 2021
# This is a "renders background" program on Pybadge

import ugame
import stage


def game_scene():
    # this function shows wave background on Pybadge

    image_bank_background = stage.Bank.from_bmp16("background.bmp")
    
    background = stage.Grid(image_bank_background, 10, 8)

    game = stage.Stage(ugame.display, 60)
    game.layers = [background]
    game.render_block()

    # repeat forever, game loop
    while True:
        pass  # just a placeholder for now


if __name__ == "__main__":
    game_scene()
